"""SQLite persistence layer: schema, lazy init/seed, connection, and repository functions."""

from .connection import (
    close_db,
    get_connection,
    init_db,
    new_id,
    to_iso,
    transaction,
    utc_now_iso,
)
from .repository import (
    QTY_EPSILON,
    Position,
    Trade,
    add_watchlist,
    delete_position,
    get_cash,
    get_position,
    insert_chat_message,
    insert_snapshot,
    insert_trade,
    list_chat_messages,
    list_positions,
    list_snapshots,
    list_watchlist,
    realized_pnl_total,
    remove_watchlist,
    set_cash,
    upsert_position,
)
from .schema import DEFAULT_CASH_BALANCE, DEFAULT_USER_ID, DEFAULT_WATCHLIST

__all__ = [
    "DEFAULT_CASH_BALANCE",
    "DEFAULT_USER_ID",
    "DEFAULT_WATCHLIST",
    "QTY_EPSILON",
    "Position",
    "Trade",
    "add_watchlist",
    "close_db",
    "delete_position",
    "get_cash",
    "get_connection",
    "get_position",
    "init_db",
    "insert_chat_message",
    "insert_snapshot",
    "insert_trade",
    "list_chat_messages",
    "list_positions",
    "list_snapshots",
    "list_watchlist",
    "new_id",
    "realized_pnl_total",
    "remove_watchlist",
    "set_cash",
    "to_iso",
    "transaction",
    "upsert_position",
    "utc_now_iso",
]
